### ISSUE TITLE
Undefined index: text at Types\BaseConverter.php line 34

### ISSUE THREAD

**Issue by ngangchill** [WouterSioen/sir-trevor-php#5]
A PHP Error was encountered

Severity: Notice

Message: Undefined index: text

Filename: Types/BaseConverter.php

Line Number: 34

**Comment by WouterSioen** [comment]
What type of data are you trying to convert? Is it a type that isn't implemented (yet)?

**Comment by ngangchill** [comment]
![capture](https://cloud.githubusercontent.com/assets/4242225/12978322/7150a072-d0fa-11e5-874c-d3dfa4f535ea.PNG)



dump();


"{"data":[{"type":"columns","data":{"columns":[{"width":6,"blocks":[{"type":"text","data":{"text":"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\ntempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\nquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\nconsequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\ncillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\nproident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n"}}]},{"width":6,"blocks":[{"type":"text","data":{"text":"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\ntempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\nquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\nconsequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\ncillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\nproident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n"}}]}],"preset":"columns-6-6"}}]}"

**Comment by ngangchill** [comment]
i think the error may be for  {"type":"columns"


![image](https://cloud.githubusercontent.com/assets/4242225/12978459/29f70d5a-d0fb-11e5-8269-0c244f9c2e8c.png)

**Comment by WouterSioen** [comment]
Hmm, this is probably a new feature in sir trevor that didn't exist yet when I created this library. I don't have a lot of time right now to implement this, but doing it should be fairly easy. A pull request would be more then welcome.

**Comment by ngangchill** [comment]
its not a new feature, i think it is deprecated in new version of trevor js .

columns block was present in Sir Trevor JS v0.4.0 , latest version 0.5.x.

i use your previous library for this.that works perfact.  "woutersioen/sir-trevor-php": "1.0", throughs error.
